---
:welcome: "=> Welcome to Calculator! Enter your name:"
:valid_name: "Make sure to use a valid name."
:hi: "=> Hi"
:retrieve_num_1: "What's the first number?"
:invalid_num: "Hmm... that doesn't look like a valid number"
:retrieve_num_2: "What's the second number?"
:operator_prompt: "What operation would you like to perform? \n1) add \n2) subtract \n3) multiply \n4) divide"
:must_choose: "Must choose 1, 2, 3, or 4"
:numbers_action: "the two numbers..."
:adding: "adding"
:subtracting: "subtracting"
:multiplying: "multiplying"
:dividing: "dividing"
:result: "The result is"
:no_zero: "You can't divide by zero!"
:another: "Do you want to perform another operation?(Y to calculate again)"
:goodbye: "Thank you for using the calculator! Good bye!"