---
en:
  welcome: "Welcome to Calculator! Enter your name:"
  valid_name: "Make sure to use a valid name."
  hi: "Hi %{name}"
  retrieve_num_1: "What's the first number?"
  invalid_num: "Hmm... that doesn't look like a valid number"
  retrieve_num_2: "What's the second number?"
  operator_prompt: "What operation would you like to perform? \n1) add \n2) subtract \n3) multiply \n4) divide"
  must_choose: "Must choose 1, 2, 3, or 4"
  numbers_action: "%{operation} the two numbers..."
  adding: "adding"
  subtracting: "subtracting"
  multiplying: "multiplying"
  dividing: "dividing"
  result: "The result is %{result}."
  no_zero: "You can't divide by zero!"
  another: "Do you want to perform another operation?(Y to calculate again)"
  goodbye: "Thank you for using the calculator! Good bye!"
es:
  welcome: "=> ¡Bienvenido a Calculadora! Introduzca su nombre:"
  valid_name: "Asegúrese de utilizar un nombre válido."
  hi: "=> Hola\n"
  retrieve_num_1: "¿Cuál es el primer número?"
  invalid_num: "Hmm... eso no parece un número válido"
  retrieve_num_2: "¿Cuál es el segundo número?"
  operator_prompt: "¿Qué operación le gustaría realizar?? \n1) agregar \n2) sustrear \n3) multiplicar \n4) dividir"
  must_choose: "Debe elegir 1, 2, 3 o 4"
  numbers_action: "los dos numeros..."
  adding: "agregando"
  subtracting: "restando"
  multiplying: "multiplicando"
  dividing: "dividiendo"
  result: "El resultado es: "
  no_zero: "¡No puedes dividir por cero!"
  another: "¿Quiere realizar otra operación? (Y volver a calcular)"
  goodbye: "¡Gracias por usar la calculadora! ¡Adiós!"
  